server:
  port: 7911
  display-name: user-thrift-service

# 数据源的配置
spring:
  datasource:
    url: jdbc:mysql://${mysql.address}:3306/db_user?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis 配置
#mybatis:
#  mapper-locations: classpath:com/joy/user/mapper/*.xml
#  type-aliases-package: com.joy.thrift.user
